export class CommonConstants {
  static readonly NUM_1: number = 1;
  static readonly NUM_2: number = 2;
  static readonly NUM_3: number = 3;
  static readonly NUM_4: number = 4;
  static readonly GRID_4: number = 4;
  static readonly GRID_6: number = 6;
  static readonly GRID_8: number = 8;
  static readonly GRID_12: number = 12;
  static readonly OFFSET_0: number = 0;
  static readonly OFFSET_1: number = 1;
  static readonly OFFSET_2: number = 2;
  static readonly OFFSET_4: number = 4;

  /**
   * Constant for font weight
   */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * Constant for item space
   */
  static readonly ITEM_SPACE: number = 12;

  /**
   * Constant for opacity
   */
  static readonly OPACITY: number = 0.6;

  /**
   * Component size percentage: 100%.
   */
  static readonly FULL_SIZE: string = '100%';

  /**
   * Bottom image size percentage: 40%.
   */
  static readonly BOTTOM_IMAGE_SIZE: string = '40%';

  /**
   * Bottom tab width percentage: 25%.
   */
  static readonly BOTTOM_TAB_WIDTH: string = '25%';

  /**
   * Bottom tab height percentage: 10%.
   */
  static readonly BOTTOM_TAB_HEIGHT: string = '10%';

  /**
   * Sidebar width percentage: 10%.
   */
  static readonly SIDEBAR_WIDTH: string = '10%';

  /**
   * Sidebar max width percentage: 15%.
   */
  static readonly SIDEBAR_WIDTH_MAX: string = '15%';

  /**
   * Sidebar min width percentage: 8%.
   */
  static readonly SIDEBAR_WIDTH_MIN: string = '8%';

  /**
   * Row width percentage: 25%.
   */
  static readonly ROW_WIDTH: string = '25%';

  /**
   * Left image size percentage: 30%.
   */
  static readonly LEFT_IMAGE_SIZE: string = '30%';

  /**
   * Left tab width percentage: 10%.
   */
  static readonly LEFT_TAB_WIDTH: string = '10%';

  /**
   * Left tab height percentage: 12.5%.
   */
  static readonly LEFT_TAB_HEIGHT: string = '12.5%';

  /**
   * Mine column height percentage: 60%.
   */
  static readonly MINE_COLUMN_HEIGHT: string = '60%';

  /**
   * Mine image location of x-axis percentage: 50%.
   */
  static readonly MINE_IMAGE_X: string = '50%';

  /**
   * Mine image location of y-axis percentage: 40%.
   */
  static readonly MINE_IMAGE_Y: string = '40%';
}